# Generated by Django 4.2.8 on 2024-01-29 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_make_default_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content_file',
        ),
        migrations.AddField(
            model_name='course',
            name='file_url',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 18, 24, 32, 486580, tzinfo=datetime.timezone.utc)),
        ),
    ]
