# Generated by Django 4.2.8 on 2024-01-29 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_remove_course_content_file_course_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 19, 0, 52, 422347, tzinfo=datetime.timezone.utc)),
        ),
    ]
