# Generated by Django 4.2.8 on 2024-01-29 18:46
import random

from django.db import migrations

course_name_list = [
    'Becoming a Football Data Analyst.html',
    'Dealing with failures and shames in life.html',
    'Elliott wave.html',
    'English for TOEFL test.html',
    'Exploring Recursive Queries in SQL and Their Functionality.html',
    'Golang programming.html',
    'How to write a plot_.html',
    'Interactive teaching.html',
    'Kierkegaard philosophy.html',
    'Labour Market.html',
    'Legal solutions to reduce child labor.html',
    'Negotiation Skills.html',
    'Overcoming Anxiety.html',
    'Pricing Schemes in Cloud Computing.html',
    'Stakeholder management according to PMbok.html',
    'Using English language in the classroom.html',
]


def forward(apps, schema_editor):
    Course = apps.get_model("edu", "Course")  # noqa
    Teacher = apps.get_model("edu", "Teacher")  # noqa
    teacher = Teacher.objects.create(username='auto-teacher', password='adDVaevd23')  # noseq
    for course_name in course_name_list:
        Course.objects.create(
            name=course_name[:-5],
            description='A basic course about ' + course_name[:-5],
            price=random.choice([200000, 250000, 350000, 500000]),
            estimate_days=random.choice([1, 3, 5, 10]),
            difficulty=random.choice([1, 2, 3, 4, 5]),
            file_url='https://raw.githubusercontent.com/SMSadegh19/CourseGenPy/main/Generated%20Outputs/' + course_name.replace(' ', '%20'),
            maker=teacher,
        )


def backward(apps, schema_editor):
    Course = apps.get_model("edu", "Course")  # noqa
    Teacher = apps.get_model("edu", "Teacher")  # noqa

    for course_name in course_name_list:
        course = Course.objects.get(name=course_name[:-5])
        course.delete()

    try:
        teacher = Teacher.objects.get(username='auto-teacher')
        teacher.delete()
    except Teacher.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('edu', '0004_course_picture_alter_course_name_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
