# Generated by Django 4.2.8 on 2024-02-03 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_remove_teacher_user_ptr_user_type_alter_course_maker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 19, 33, 21, 568735, tzinfo=datetime.timezone.utc)),
        ),
    ]
