# Generated by Django 4.2.8 on 2024-02-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_alter_courseenrollment_conversation_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='date_expired',
        ),
    ]
